name: Build Release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build
      run: swift build -c release --arch arm64 --arch x86_64

    - name: Create release artifact
      uses: actions/upload-artifact@v3
      with:
        name: xcresultparser
        path: .build/apple/Products/Release/xcresultparser

    - name: Get release upload URL
      id: get_release_upload_url
      run: echo "RELEASE_UPLOAD_URL=${{ github.event.release.upload_url }}" >> $GITHUB_ENV

    - name: Upload release asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ env.RELEASE_UPLOAD_URL }}
        asset_path: .build/apple/Products/Release/xcresultparser
        asset_name: xcresultparser
        asset_content_type: application/octet-stream
